add support of min and max time limit
withpeterjoseph/react-time-range pull request #6
Opened 2021-05-12 14:00 UTC by okobsamoht

add support of min and max time limit

2021-05-14 08:59 UTC, cadbox1 requested changes
hi @okobsamoht, thanks for the PR!

My friend, Pete, made this project but sadly he passed and handed it over to me so I'm glad you could find some value in it and I'm sure he would too.

Just a small comment about the required fields, which would be a breaking change for other users. if you could change that I'll merge it in. 

also, for future PRs it's preferable to maintain the current code style. It was pretty hard to review but I'm not too fussed and we could probably do with some code styling tools in the project.

were you interested in becoming a maintainer by any chance?

2021-05-14 08:59 UTC, cadbox1 commented on src/index.js
> +    minStartMoment: PropTypes.string.isRequired,
I think these should be optional, not required

2021-05-23 17:19 UTC, okobsamoht commented on src/index.js
> +    minStartMoment: PropTypes.string.isRequired,
Hi Cadel! 
I'm sad to hear that bad news.
For the required fields ill change them to optional and commit.
I'll be glad to be part of the maintainers of this great project.
Thanks

2021-05-23 18:38 UTC, okobsamoht commented
if you don't mind, i'll cancel the PR and do it again.

2021-05-23 18:38 UTC, closed without merging

2021-05-24 06:23 UTC, cadbox1 commented
no worries, looking forward to it! thanks!